//Pacote
package validacoes;

//Biblioteca
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.junit.After;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
	
//Classe
public class validaPreco {

      //Atributo	
	  private WebDriver driver;
	  
	  //Métodos
	  @Before
	  public void setUp() {
	    System.setProperty("webdriver.chrome.driver","driver/chromedriver/chromedriver.exe");
	    driver = new ChromeDriver();
	    
	  }
	  @After
	  public void tearDown() {
	    //driver.quit();
	  }
	  @Test
	  public void magalu() {
	    driver.get("https://www.magazineluiza.com.br/");
	    
	    driver.manage().window().setSize(new Dimension(1382, 736));
	    driver.findElement(By.id("input-search")).click();
	    driver.findElement(By.id("input-search")).sendKeys("Relógio de pulso");
	    driver.findElement(By.id("input-search")).sendKeys(Keys.ENTER);
	    driver.findElement(By.id("input-search")).sendKeys(Keys.DOWN);
	    
	    
	    /*driver.findElement(By.cssSelector(".sc-kSpoSR")).click();
	    assertThat(driver.findElement(By.cssSelector(".sc-fezjOJ:nth-child(1) .sc-kexyCK")).getText(), is("Relógio Skmei Original Masculino de Pulso Digital Esportivo SKM-1251"));
	    driver.findElement(By.cssSelector(".sc-fezjOJ:nth-child(1) .sc-kexyCK")).click();
	    driver.findElement(By.cssSelector(".showcase-product__container-img")).click();
	    driver.findElement(By.cssSelector(".js-pop-product > .button__close")).click();
	    assertThat(driver.findElement(By.cssSelector(".price-template")).getText(), is("por R$ 129,90\\\\nem 2x de R$ 64,95 sem juros"));
	    */  
	  }
	}
